### ISSUE TITLE
BF 4.3 Update (closed)

### ISSUE THREAD

**Issue by Zuldan** [mrRobot62/betaflight_processing#3]
@mrRobot62 would it be possible for you to update this flow chart for BF 4.3? It’s really good. I think a lot of people would find it useful.

**Comment by mrRobot62** [comment]
Hi Zuldan,
yes, I will update the processing chart as soon as possible. I'm waiting as long ,as Betaflight publish an official BF 4.3 release to avoid useless work.

Honestely I don't know how long this work will take

**Comment by Zuldan** [comment]
Thank you so much for responding. I understand. Happy to wait!

**Comment by mrRobot62** [comment]
Update for BF 4.3 is available - please follow links in README.MD

**Comment by Zuldan** [comment]
Thank you so much. Love it! It’s going on the wall in the man cave.
